### ISSUE TITLE
New Comments Testing

### ISSUE THREAD

**Issue by santip5** [santip5/Project6#12]
As a student, I want to test adding new comments, so that we can make sure that it is working according to the requirements and expectations. Refer to #10 for requirements.

**Comment by trevor-scofield** [comment]
Screenshot of the test comment that was made saved in MongoDB
![Screenshot 2023-11-13 154026](https://github.com/santip5/Project6/assets/20018573/36994d22-d356-4875-961e-be8ceda72510)
