### ISSUE TITLE
Registration and Passwords Testing

### ISSUE THREAD

**Issue by santip5** [santip5/Project6#18]
As a student, I want to test registering a new user using a password, so that we can make sure that it is working according to the requirements and expectations. Refer to #16 for requirements.

**Comment by trevor-scofield** [comment]
MongoDB was able to receive the registration of a new user
![Screenshot 2023-11-13 154120](https://github.com/santip5/Project6/assets/20018573/79c4daed-6051-499b-a88c-e15792eabeef)
